spring.application.name=backend
server.port=${PORT:8080}


# Database Configuration
spring.datasource.url=jdbc:postgresql://<REAL_HOST>/<REAL_DB>?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${ADMIN_EMAIL}
spring.mail.password=${EMAIL_PASSCODE}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# HR Notification Config
skilljobbie.hr.email=${HR_EMAIL}

# Google Sheets Configuration
google.sheets.spreadsheet.id=${GOOGLE_SHEET}
google.sheets.credentials.file.path=${CLASSPATH}
