spring.application.name=backend
server.port=8080




# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${admin_email}
spring.mail.password=${email_passcode}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# HR Notification Config
skilljobbie.hr.email=${hr_email}

# Google Sheets Configuration
google.sheets.spreadsheet.id=${Google_Sheet}
google.sheets.credentials.file.path=${classpath}
